
// DO NOT EDIT - Autogenerated by Overlord
const std = @import("std");
const Library = @import("libs/library.zig").Library;
const sdkPath = @import("libs/library.zig").sdkPath;


const hello_world = @import("hello_world/ikuy_build.zig");



pub fn build(b: *std.build.Builder) !void {
  var libraryPackages = std.StringHashMap(Library).init(b.allocator);
  try libraryPackages.put("base", Library{ .name = "base", .path = sdkPath("/base/build.zig") });

  hello_world.build(b, libraryPackages);
}
